version: "3.7"

services:
  chibisafe:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
      - WATCHPACK_POLLING=true
    volumes:
      - ./packages/next:/app/packages/next
      - chibisafe_next_node_modules:/app/packages/next/node_modules
    expose:
      - 8001
    restart: unless-stopped

  chibisafe_server:
    image: chibisafe/chibisafe-server:dev
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - ./database:/app/database:rw
      - ./uploads:/app/uploads:rw
      - ./logs:/app/logs:rw
    expose:
      - 8000
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./uploads:/app/uploads:ro
    ports:
      - 24424:80
    environment:
      - BASE_URL=":80"
    restart: unless-stopped

  minio:
    image: minio/minio
    volumes:
      - ./minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
      MINIO_VOLUMES: /data
    command: minio server --console-address ":9001"

volumes:
  chibisafe_next_node_modules:
